# SITE SETUP

# Appearance
appearance:
  mode: system
  color: orange

# SEO
marketing:
  seo:
    site_type: ResearchOrganization
    local_business_type: ''
    org_name: 'NAME'
    description: "Making the world's complex problems accessible."
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      # text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.png"
    # button:
    #   enable: true
    #   text: "Get Tickets"
    #   url: "https://www.eventbrite.com/"
    # show_search: true
    show_theme_chooser: false

# Site footer
footer:
  block: minimal
  copyright:
    notice: '© {year} NAME. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true
# footer:
#   block: sitemap
#   content:
#     logo:
#       text: "Pythonic Media"
#     tagline: ""
#   design:
#     columns: 2
#   copyright:
#     notice: '© {year} Pythonic Media. This work is licensed under GNU GPL v3.0'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: github-dark
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: ''
    content_dir: posts
    branch: main

i_am_a_sponsor: true